.PHONY: help django migrate makemigrations collectstatic tw-dev tw-build npm-install clean

help:
    @echo "Common commands:"
    @echo "  make django         # Start Django dev server"
    @echo "  make migrate        # Apply database migrations"
    @echo "  make makemigrations # Create new migrations"
    @echo "  make collectstatic  # Collect static files"
    @echo "  make tw-dev         # Run Tailwind watcher with Django"
    @echo "  make tw-build       # Build Tailwind CSS once"
    @echo "  make npm-install    # Install npm dependencies"
    @echo "  make clean          # Remove pycache and static build files"

django:
    python manage.py runserver

migrate:
    python manage.py migrate

makemigrations:
    python manage.py makemigrations

collectstatic:
    python manage.py collectstatic --noinput

tw-dev:
    cd theme/static_src && npx tailwindcss -i ./src/input.css -o ../static/css/dist/output.css --watch

tw-build:
    cd theme/static_src && npx tailwindcss -i ./src/input.css -o ../static/css/dist/output.css --minify

npm-install:
    cd theme/static_src && npm install

clean:
    find . -name "*.pyc" -delete
    find . -name "__pycache__" -type d -exec rm -rf {} +
    rm -rf theme/static/css/dist/*