# Generated by Django 5.2.6 on 2025-10-16 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_church'),
    ]

    operations = [
        migrations.RenameField(
            model_name='church',
            old_name='longditude',
            new_name='longitude',
        ),
    ]
