# Generated by Django 5.2.6 on 2025-10-17 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_longditude_church_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='church',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='church',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
