name: Project Board Automation

on:
  issues:
    types: [opened, closed, reopened, labeled, assigned, unassigned]
  pull_request:
    types: [opened, closed, reopened, ready_for_review, converted_to_draft]

jobs:
  project-board-automation:
    runs-on: ubuntu-latest
    steps:
      - name: Add new issues to project board
        if: github.event.action == 'opened' && github.event_name == 'issues'
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: ${{ vars.PROJECT_URL }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Move assigned issues to In Progress
        if: github.event.action == 'assigned' && github.event_name == 'issues'
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: ${{ vars.PROJECT_URL }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Move closed issues to Done
        if: github.event.action == 'closed' && github.event_name == 'issues'
        uses: actions/add-to-project@v0.5.0
        with:
          project-url: ${{ vars.PROJECT_URL }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Comment on MoSCoW labeled issues
        if: github.event.action == 'labeled' && contains(github.event.label.name, 'MUST HAVE')
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '🎯 This issue has been marked as **MUST HAVE** priority. It will be prioritized in the backlog and should be addressed in the current release cycle.'
            })

      - name: Check for missing priority labels
        if: github.event.action == 'opened' && github.event_name == 'issues'
        uses: actions/github-script@v7
        with:
          script: |
            const issue = context.payload.issue;
            const moscowLabels = ['MUST HAVE', 'SHOULD HAVE', 'COULD HAVE', 'WONT HAVE'];
            const hasPreiorityLabel = issue.labels.some(label => moscowLabels.includes(label.name));
            
            if (!hasPreiorityLabel && issue.labels.some(label => label.name.includes('USER STORY'))) {
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: '⚠️ This user story is missing a MoSCoW priority label. Please add one of: `MUST HAVE`, `SHOULD HAVE`, `COULD HAVE`, or `WONT HAVE`.'
              });
            }